platform :ios, '10.0'

use_frameworks!

target 'SwiftyDeck_Example' do
  pod 'SwiftyDeck', :path => '../'

  target 'SwiftyDeck_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'SwiftLint'
  end
end
