use_frameworks!

target 'SwiftyDeck_Example' do
  pod 'SwiftyDeck', :path => '../'

  target 'SwiftyDeck_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
