disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo # Not necessary
  - class_delegate_protocol # Not necessary
# - closing_brace
  - closure_parameter_position
# - colon
# - comma
  - compiler_protocol_init
# - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
# - empty_enum_arguments
# - empty_parameters
# - empty_parentheses_with_trailing_closure
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - notification_center_detachment
# - opening_brace
  - operator_whitespace
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
# - redundant_discardable_let
# - redundant_objc_attribute
# - redundant_optional_initialization
# - redundant_set_access_control
# - redundant_string_enum_value
# - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
#  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
#  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
#  - weak_delegate
  - xctfail_message
included: # paths to include during linting. `--path` is ignored if present.
  - Connected2.me
#  - Connected2UITests
#  - Connected2UnitTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# Overridden rules

# force_cast: warning # implicitly

weak_delegate:
    severity: error

opt_in_rules:
  - unused_import
  - private_action
  - empty_count
  - toggle_bool
  - empty_string
  - empty_xctest_method
  - redundant_nil_coalescing
  - redundant_type_annotation
  - identical_operands
  #- discouraged_optional_boolean // Not really.
#  - closure_end_indentation
#cyclomatic_complexity:
#  warning: 20
#  error: 25
