language:
  - swift

osx_image: xcode11

xcode_project: Example/SwiftyDeck.xcodeproj # path to your xcodeproj folder
xcode_scheme: SwiftyDeck_Tests
xcode_destination: platform=iOS Simulator,name=iPhone X,OS=12.1

after_success:
  - bash <(curl -s https://codecov.io/bash)
