language:
  - swift

osx_image: xcode11

# before_install:
#  - pod repo update
#  - pod install --project-directory=Example

xcode_workspace: Example/SwiftyDeck.xcworkspace # path to your xcodeproj folder
xcode_scheme: SwiftyDeck-Example
xcode_destination: platform=iOS Simulator,name=iPhone X,OS=12.1


after_success:
  - bash <(curl -s https://codecov.io/bash)
